name: student_app_provider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
